# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/MilanoWaterProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/MilanoWaterProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/MilanoWaterProject/CMakeFiles /home/pi/MilanoWaterProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/MilanoWaterProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named mylib

# Build rule for target.
mylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mylib
.PHONY : mylib

# fast build rule for target.
mylib/fast:
	$(MAKE) $(MAKESILENT) -f mylib/CMakeFiles/mylib.dir/build.make mylib/CMakeFiles/mylib.dir/build
.PHONY : mylib/fast

#=============================================================================
# Target rules for targets named irrigationmonitor

# Build rule for target.
irrigationmonitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irrigationmonitor
.PHONY : irrigationmonitor

# fast build rule for target.
irrigationmonitor/fast:
	$(MAKE) $(MAKESILENT) -f IrrigationMonitor/CMakeFiles/irrigationmonitor.dir/build.make IrrigationMonitor/CMakeFiles/irrigationmonitor.dir/build
.PHONY : irrigationmonitor/fast

#=============================================================================
# Target rules for targets named tankmonitor

# Build rule for target.
tankmonitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tankmonitor
.PHONY : tankmonitor

# fast build rule for target.
tankmonitor/fast:
	$(MAKE) $(MAKESILENT) -f TankMonitor/CMakeFiles/tankmonitor.dir/build.make TankMonitor/CMakeFiles/tankmonitor.dir/build
.PHONY : tankmonitor/fast

#=============================================================================
# Target rules for targets named monitor

# Build rule for target.
monitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monitor
.PHONY : monitor

# fast build rule for target.
monitor/fast:
	$(MAKE) $(MAKESILENT) -f Monitor/CMakeFiles/monitor.dir/build.make Monitor/CMakeFiles/monitor.dir/build
.PHONY : monitor/fast

#=============================================================================
# Target rules for targets named wellmonitor

# Build rule for target.
wellmonitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wellmonitor
.PHONY : wellmonitor

# fast build rule for target.
wellmonitor/fast:
	$(MAKE) $(MAKESILENT) -f WellMonitor/CMakeFiles/wellmonitor.dir/build.make WellMonitor/CMakeFiles/wellmonitor.dir/build
.PHONY : wellmonitor/fast

#=============================================================================
# Target rules for targets named housemonitor

# Build rule for target.
housemonitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 housemonitor
.PHONY : housemonitor

# fast build rule for target.
housemonitor/fast:
	$(MAKE) $(MAKESILENT) -f HouseMonitor/CMakeFiles/housemonitor.dir/build.make HouseMonitor/CMakeFiles/housemonitor.dir/build
.PHONY : housemonitor/fast

#=============================================================================
# Target rules for targets named alert

# Build rule for target.
alert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alert
.PHONY : alert

# fast build rule for target.
alert/fast:
	$(MAKE) $(MAKESILENT) -f SysAlert/CMakeFiles/alert.dir/build.make SysAlert/CMakeFiles/alert.dir/build
.PHONY : alert/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f SysTest/CMakeFiles/test.dir/build.make SysTest/CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named log

# Build rule for target.
log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 log
.PHONY : log

# fast build rule for target.
log/fast:
	$(MAKE) $(MAKESILENT) -f SysLog/CMakeFiles/log.dir/build.make SysLog/CMakeFiles/log.dir/build
.PHONY : log/fast

#=============================================================================
# Target rules for targets named blynkWater

# Build rule for target.
blynkWater: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blynkWater
.PHONY : blynkWater

# fast build rule for target.
blynkWater/fast:
	$(MAKE) $(MAKESILENT) -f Blynk/CMakeFiles/blynkWater.dir/build.make Blynk/CMakeFiles/blynkWater.dir/build
.PHONY : blynkWater/fast

#=============================================================================
# Target rules for targets named blynkAlert

# Build rule for target.
blynkAlert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blynkAlert
.PHONY : blynkAlert

# fast build rule for target.
blynkAlert/fast:
	$(MAKE) $(MAKESILENT) -f BlynkAlert/CMakeFiles/blynkAlert.dir/build.make BlynkAlert/CMakeFiles/blynkAlert.dir/build
.PHONY : blynkAlert/fast

#=============================================================================
# Target rules for targets named blynkLog

# Build rule for target.
blynkLog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blynkLog
.PHONY : blynkLog

# fast build rule for target.
blynkLog/fast:
	$(MAKE) $(MAKESILENT) -f BlynkLog/CMakeFiles/blynkLog.dir/build.make BlynkLog/CMakeFiles/blynkLog.dir/build
.PHONY : blynkLog/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... alert"
	@echo "... blynkAlert"
	@echo "... blynkLog"
	@echo "... blynkWater"
	@echo "... housemonitor"
	@echo "... irrigationmonitor"
	@echo "... log"
	@echo "... monitor"
	@echo "... mylib"
	@echo "... tankmonitor"
	@echo "... test"
	@echo "... wellmonitor"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

